### ISSUE TITLE
Tutorial doesn't work

### ISSUE THREAD

**Issue by DraconPern** [remix-run/indie-stack#167] opened 2022-10-14 03:46 UTC
### Have you experienced this bug with the latest version of the template?

Yes

### Steps to Reproduce

Tried to do remix tutorial at https://remix.run/docs/en/v1/tutorials/blog

when I run the command it fails to complete. npx create-remix@latest --template remix-run/indie-stack blog-tutorial

### Expected Behavior

Create a remix tutorial

### Actual Behavior

Running seed command `node --require tsconfig-paths/register prisma/seed.js` ...
TypeError: Cannot read properties of undefined (reading 'hash')
    at seed (E:\blog-tutorial\prisma\seed.js:15:39)

An error occured while running the seed command:
Error: Command failed with exit code 1: node --require tsconfig-paths/register prisma/seed.js
🚨 Oops, remix.init failed

Command failed: npm run setup

**Comment by machour** [comment] 2022-10-14 04:18
Duplicate of #164

**Closed by machour** 2022-10-14 04:18 UTC
