### ISSUE TITLE
LiveReload not functional on fresh install

### ISSUE THREAD

**Issue by BiffBish** [remix-run/indie-stack#34] opened 2022-03-26 18:08 UTC
Im using `npm run dev `and when it starts running my changes are not auto reloading.

![image](https://user-images.githubusercontent.com/42410516/160251929-682272b6-c60a-43c3-9a10-4838ab85e6c2.png)

**Comment by moishinetzer** [comment] 2022-03-27 10:23
Could you please provide more info: setup versions, steps to reproduce, os

I may be wrong but that looks like wsl, do you still have this issue when using cmd or git bash?

**Comment by BiffBish** [comment] 2022-03-27 15:37
I had to use wsl to get everything functional. lots of hours debugging. I just ran `npx create-remix --template remix-run/indie-stack` and followed all the instructions. it is WSL and was the only solution i have found to work, its WSL Ubuntu-20.04

**Comment by brandonpittman** [comment] 2022-04-01 13:57
I'm on a Mac and having the same issue, the basic template install says it's rebuilding, but I have to manually reload the browser to see anything.

**Comment by brandonpittman** [comment] 2022-04-01 23:02
This was the issue that caught me:

https://github.com/remix-run/remix/issues/296

**Comment by mcansh** [comment] 2022-04-01 23:21
> This was the issue that caught me:
> 
> 
> 
> https://github.com/remix-run/remix/issues/296

gotcha, we had PR that automatically found a new port if it was taken, but the port didn't properly make it to the browser, the next release has another fix for that, which should be out early next week

**Comment by machour** [comment] 2022-07-11 12:00
This should be fixed by now, feel free to reopen this issue if it's not the case.

**Closed by machour** 2022-07-11 12:00 UTC
